# configuration for https://codecov.io
ignore:
  - "sacroml/config"
  - "sacroml/main.py"
  - "sacroml/preprocessing"
  - "sacroml/safemodel/classifiers/new_model_template.py"
  - "examples"
  - "setup.py"
  - "user_stories"
