[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pylint]
master.py-version = "3.9"
reports.output-format = "colorized"
disable = [
    "invalid-name",
    "no-member",
    "duplicate-code",
]

[tool.pylint.messages_control]
enable = [
    "useless-suppression",
]

[tool.pylint.design]
max-args = 5  # Maximum number of arguments for function / method (see R0913).
max-attributes = 7  # Maximum number of attributes for a class (see R0902).
max-branches = 12  # Maximum number of branch for function / method body (see R0912).
max-locals = 15  # Maximum number of parents for a class (see R0914).
max-parents = 7  # Maximum number of parents for a class (see R0901).
max-public-methods = 20  # Maximum number of public methods for a class (see R0904).
max-returns = 6  # Max number of return / yield for function / method body (see R0911).
max-statements = 50  # Max number of statements in function / method body (see R0915).
min-public-methods = 2  # Minimum number of public methods for a class (see R0903).

[tool.pylint.format]
max-line-length = 100  # Maximum number of characters on a single line.
max-module-lines = 1000  # Maximum number of lines in a module.
