training_artefacts_dir: "training_artefacts"
target_model: "model.pkl"
target_results: "target.json"
outfile: "summary.txt"
attack_results: "attack_results.json"
dataset_filename: "../user_stories_resources/dataset_26_nursery.csv"

# User story 3
x_train_path: "trainX.txt"
y_train_path: "trainy.txt"
x_test_path: "testX.txt"
y_test_path: "testy.txt"
attack_output_name: "attack_output"

# User story 2
train_indices: "indices_train.txt"
test_indices: "indices_test.txt"
