---
name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.cff'
      - 'setup.py'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install .

      - name: pytest and report coverage
        run: |
          pytest --cov=./ --cov-report=xml
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
...
