---
name: Tests Manually Run

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.os }}-Python${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and pytest
        run: pip install . pytest

      - name: Run pytest
        run: pytest .
...
